CREATE TABLE public.characters (id uuid DEFAULT gen_random_uuid() NOT NULL, story_id uuid NOT NULL, name text NOT NULL, "position" smallint NOT NULL, persona text NOT NULL);
ALTER TABLE public.characters ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.characters ADD CONSTRAINT characters_name_usable CHECK (length(btrim(name)) >= 1 AND length(btrim(name)) <= 60);
ALTER TABLE public.characters ADD CONSTRAINT characters_owned_id UNIQUE (id, story_id);
ALTER TABLE public.characters ADD CONSTRAINT characters_persona_usable CHECK (length(btrim(persona)) >= 1 AND length(btrim(persona)) <= 2000);
ALTER TABLE public.characters ADD CONSTRAINT characters_pkey PRIMARY KEY (id);
ALTER TABLE public.characters ADD CONSTRAINT characters_position_usable CHECK ("position" >= 1 AND "position" <= 4);
ALTER TABLE public.characters ADD CONSTRAINT characters_story_id_fkey FOREIGN KEY (story_id) REFERENCES public.stories(id) ON DELETE RESTRICT;
ALTER TABLE public.characters ADD CONSTRAINT characters_story_id_name_key UNIQUE (story_id, name);
ALTER TABLE public.characters ADD CONSTRAINT characters_story_id_position_key UNIQUE (story_id, "position") DEFERRABLE INITIALLY DEFERRED;
GRANT MAINTAIN, REFERENCES, TRIGGER, TRUNCATE ON public.characters TO anon;
GRANT MAINTAIN, REFERENCES, SELECT, TRIGGER, TRUNCATE ON public.characters TO authenticated;
GRANT ALL ON public.characters TO service_role;
CREATE POLICY characters_select_authenticated ON public.characters FOR SELECT TO authenticated USING (true);
CREATE TABLE public.episode_characters (episode_id uuid NOT NULL, character_id uuid NOT NULL, story_id uuid NOT NULL, at smallint NOT NULL);
ALTER TABLE public.episode_characters ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.episode_characters ADD CONSTRAINT episode_characters_at_usable CHECK (at >= 1 AND at <= 3);
ALTER TABLE public.episode_characters ADD CONSTRAINT episode_characters_character_fkey FOREIGN KEY (character_id, story_id) REFERENCES public.characters(id, story_id) ON DELETE RESTRICT;
ALTER TABLE public.episode_characters ADD CONSTRAINT episode_characters_episode_id_at_key UNIQUE (episode_id, at) DEFERRABLE INITIALLY DEFERRED;
ALTER TABLE public.episode_characters ADD CONSTRAINT episode_characters_pkey PRIMARY KEY (episode_id, character_id);
GRANT MAINTAIN, REFERENCES, TRIGGER, TRUNCATE ON public.episode_characters TO anon;
GRANT MAINTAIN, REFERENCES, SELECT, TRIGGER, TRUNCATE ON public.episode_characters TO authenticated;
GRANT ALL ON public.episode_characters TO service_role;
CREATE INDEX episode_characters_story_idx ON public.episode_characters (story_id, at);
CREATE INDEX episode_characters_character_idx ON public.episode_characters (character_id);
CREATE POLICY episode_characters_select_authenticated ON public.episode_characters FOR SELECT TO authenticated USING (true);
ALTER TABLE public.episodes ADD CONSTRAINT episodes_owned_id UNIQUE (id, story_id);
ALTER TABLE public.episode_characters ADD CONSTRAINT episode_characters_episode_fkey FOREIGN KEY (episode_id, story_id) REFERENCES public.episodes(id, story_id) ON DELETE CASCADE;
